# Generated by Django 5.1.2 on 2024-11-15 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0022_cardpost_is_finalized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='frame_completed',
        ),
    ]
